name: Deploy Discord Bot

on:
  push:
    branches:
      - main  
  schedule:
      - cron: "0 */3 * * *"  # 每 6 小時執行一次
concurrency:
  group: "deploy-discord-bot"
  cancel-in-progress: true  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 您可以根據需要選擇其他版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install google
          pip install google-generativeai==0.2.0
          pip install discord
          pip install -U discord.py
          pip install python-dotenv
          
      - name: Run bot
        env:
          GEMINI_TOKEN: ${{ secrets.GEMINI_TOKEN }}
          DCBOT_TOKEN: ${{ secrets.DCBOT_TOKEN }}
        run: python main.py
